DROP TABLE USER IF EXISTS ;

CREATE TABLE USER (
  id BIGINT generated BY DEFAULT AS identity,
  username VARCHAR (40),
  NAME VARCHAR (20),
  age INT (3),
  balance DECIMAL (10, 2),
  PRIMARY KEY (id)
);
